import 'server-only'
import { Metadata } from 'next'
import './globals.css'

//import { Inter } from 'next/font/google'

import { Header } from '@/components/header/header'
import { Footer } from '@/components/footer/footer'
import { Icon } from '@/components/icon/icon';

//const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body>
				<div className="App">
					<Header/>
					<main>
						{children}
					</main>
					<Footer/>
					<div className="background-cloud">
						<Icon name="cloud"/>
					</div>
				</div>
			</body>
		</html>
  	)
}

export default RootLayout;