import { Metadata } from 'next'
import './globals.css'
//import 'bootstrap/dist/css/bootstrap.min.css';
import { Inter } from 'next/font/google'

import { Header } from '@/components/header/header'
import { Footer } from '@/components/footer/footer'

/*import { CacheProvider, EmotionCache } from '@emotion/react';
import createEmotionCache from './createEmotionCache';

const clientSideEmotionCache = createEmotionCache();*/
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
	return (
      <html lang="en">
        <body className={inter.className}>
          <Header/>
          <main>
            {children}
          </main>
          <Footer/>
          </body>
      </html>
  )
}
